### ISSUE TITLE
[BUG] Introduction of Ionic added noise to unit test execution in projects utilizing Kirby

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#198]
**Describe the bug**
After ionic was introduced in Kirby, usages of KirbyModule, from a jasmine unit test has started producing the following output:

```
TypeError: Class extends value [object HTMLDivElement] is not a constructor or null
    at eval (eval at <anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:6:1970), <anonymous>:3:24)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:6:2028
    at Array.forEach (<anonymous>)
    at t (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:6:1718)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:9:283
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:289:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:390:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:150:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:889:1, 'TypeError: Class extends value [object HTMLDivElement] is not a constructor or null
    at eval (eval at <anonymous> (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:6:1970), <anonymous>:3:24)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:6:2028
    at Array.forEach (<anonymous>)
    at t (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:6:1718)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/@ionic/core/dist/esm/es5/ionic.core.js:9:283
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:391:1)
    at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:289:1)
    at ZoneDelegate../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:390:1)
    at Zone../node_modules/zone.js/dist/zone.js.Zone.run (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:150:1)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone.js:889:1'
```

**To Reproduce**
1. Create a project with a unit test using a Kirby-component (importing `KirbyModule`)
2. Execute the unit test
3. See the test execution passing (if the test is valid) - but regardless of validity "spewing" errors / stacktraces to the console.

**Kirby version**
 - LATEST

**Expected behavior**
No stacktraces are printed to the console

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 10.14.3

**Native (please complete the following information):**
N/A

**Additional context**

**Comment by jakobe** [comment]
Won't fix, related to the way team 3 did their tests 😋
